### ISSUE TITLE
Media issues in posts

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#40]
In conference posts various issues with the media 
-pdf's
-images
-videos 
sometimes load and display correctly and other times do not... in the same post...
I have tried to reload and change around, but can't seem to solve the display issue.

**Comment by bhavesh-activatemedia** [comment]
To investigate why code is being displayed rather than the image

**Comment by andreafalzetti** [comment]
Can you link an example with this error @karinapriajina ?

**Comment by karinapriajina** [comment]
http://dcaf-ua.activatemedia.com/monitoring-ukraines-security-governance-challenges-security-sector-governance-the-role-of-democratic-institutions-international-best-practices/

See "Resources" section, the first presentation is not displaying as should. This also happened to videos, I had to delete, reload and update a couple of times and one of those randomly worked and they are finally there.... but I have no idea why they wouldn't load before and why they did after a few times...a mystery

**Comment by andreafalzetti** [comment]
The issue was caused by the hotlinker plugin, the one that add hyperlinks to the text that contain Topics. The filename contains "Gender" that is a Topic so there was a conflict between the 2 codes.

I have set the hotlinker to only add a link where the topic has 2 spaces on the side for example if in the text appears "... Gender ..."  and this has fixed the issue with the image.

**Comment by karinapriajina** [comment]
Thank you Andrea! A doubt: does this mean I have to do something specific to allow/arrest linking in text?

**Comment by andreafalzetti** [comment]
You are welcome! 😃  The hotlinking happens automatically and there is no arrest functionality at the moment.
