### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by bhavesh-activatemedia** [ActivateMedia/DCAF-Ukraine#46]
Authors field is not appearing on the front end but is being added in the CMS.

**Comment by andreafalzetti** [comment]
Author and ISBN code have been added

**Comment by karinapriajina** [comment]
Many thanks Andrea! :)

**Comment by karinapriajina** [comment]
Could we Possibly make the publication year visible too?
Another question: the layout in the publications listing has changed hasn't it? #32 The description text is below the thumbnail, it didn't used to be like that...it used to be next to it in order to fit more publications into the screen? True or am I seeing things?

**Comment by andreafalzetti** [comment]
@karinapriajina I have added the publishing year in the publication page, I think the layout is back to normal now, that was just a rendering error caused by some code that we have adjusted

**Comment by karinapriajina** [comment]
Thank you Andrea! :)
