### ISSUE TITLE
 Search bar issues

### ISSUE THREAD

**Issue by karinapriajina** [ActivateMedia/DCAF-Ukraine#62]
http://ukrainesecuritysector.com/tools-and-other-resources__trashed/presentations/  (trashed?)
http://ukrainesecuritysector.com/topic/procurement/monitoring-procurement/ (no sure this is an issue)
http://ukrainesecuritysector.com/marsad_actors/international-organisations/ (there is marsad_actors in all the actors. Marsad needs to go)
http://ukrainesecuritysector.com/category/news/ ('read more' does not appear to be activate here)
Search results leading to old pages http://ukrainesecuritysector.com/anti-corruption/ (searched term: compendium, result No 2, 3)
Overall results of search bar: incoherent. 
I would like them to point to topics first and publications second and then everything else. For example if I search for "Anti-Corruption" I would like for the topic to appear as first search result and for publications related to the topic to appear next.
Layout of the search results listing is not very user friendly. Could we have links to the titles directly instead of "read more" setting?

**Comment by andreafalzetti** [comment]
- I emptied the trash and this page is now deleted  http://ukrainesecuritysector.com/tools-and-other-resources__trashed/presentations/ (trashed?)
- I can't see the problem here?
  http://ukrainesecuritysector.com/topic/procurement/monitoring-procurement/ (no sure this is an issue)
- all marsad_actors have been renamed before going live 
  http://ukrainesecuritysector.com/marsad_actors/international-organisations/ (there is marsad_actors in all the actors. Marsad needs to go)
- read more link fixed
  http://ukrainesecuritysector.com/category/news/ ('read more' does not appear to be activate here)
- Please open the [Pages](http://ukrainesecuritysector.com/wp-admin/edit.php?post_type=page) and trash the one you don't need anymore
  Search results leading to old pages http://ukrainesecuritysector.com/anti-corruption/ (searched term: compendium, result No 2, 3)
- the site is running [relevanssi](https://www.relevanssi.com) which is a plugin that improves the search. There are certain settings, I went through all of them but I couldn't find anything that allows your requirements. There is a premium version but I'm not sure it gives us what you need. If you formulate a request, we can send it to the [customer support](https://www.relevanssi.com/contact/).
  Overall results of search bar: incoherent. 
  I would like them to point to topics first and publications second and then everything else. For example if I search for "Anti-Corruption" I would like for the topic to appear as first search result and for publications related to the topic to appear next.
- I have improved the layout (links, pagination) of the search results page (eg. http://ukrainesecuritysector.com/?s=Anti-Corruption)
  Layout of the search results listing is not very user friendly. Could we have links to the titles directly instead of "read more" setting?

**Comment by karinapriajina** [comment]
Dear Andrea, 
Thanks a lot for taking care of these!

"I can't see the problem here?
http://ukrainesecuritysector.com/topic/procurement/monitoring-procurement/ (no sure this is an issue)"
The last part of the mentioned navigation address does not exactly correspond to the reality. The path is: Procurement > Procurement Monitoring & Evaluation

I will look through the pages (with great distress related to deleting things, as this is how I created a problem last time....)

Search bar, thank you, that looks much better!
