### ISSUE TITLE
Set up Ukrainian Homepage

### ISSUE THREAD

**Issue by andreafalzetti** [ActivateMedia/DCAF-Ukraine#73]

**Comment by karinapriajina** [comment]
![image](https://cloud.githubusercontent.com/assets/15872221/20754230/460320e2-b70a-11e6-99eb-9aac2fed2c24.png)

**Comment by karinapriajina** [comment]
![image](https://cloud.githubusercontent.com/assets/15872221/20754249/5c3c482a-b70a-11e6-87ca-99008c02b2b5.png)

**Comment by karinapriajina** [comment]
There's a lot of stuff missing from the Ukrainian front end.... Is there a way for you to tell me when Viktor logged in last (except for today, because that's me) and what he did there? I remember that he was working on Tools and Other Resources (with visual composer) and that some of it was already translated but maybe I had dreamt that because it's no longer there (if it ever was)...

**Comment by andreafalzetti** [comment]
@karinapriajina I removed the black title, added the missing icons, flagged few articles as favourite so we can see some boxes below.

**Comment by andreafalzetti** [comment]
I also added the translation of "Read more" (Далі) into WPML just to confirm this is working and it can be edited by Viktor at any time, for any string available for translation in WPML -> String translation.

**Comment by andreafalzetti** [comment]
Andrea to check tags of http://ukrainesecuritysector.com/uk/%d0%bc%d0%be%d0%bd%d1%96%d1%82%d0%be%d1%80%d0%b8%d0%bd%d0%b3-%d0%b2%d0%b8%d0%ba%d0%bb%d0%b8%d0%ba%d1%96%d0%b2-%d1%83%d1%80%d1%8f%d0%b4%d1%83%d0%b2%d0%b0%d0%bd%d0%bd%d1%8e-%d1%81%d0%b5%d0%ba%d1%82-3/
